import docker
import os
import shutil
from pathlib import Path

class ExecutionSandbox:
    def __init__(self, workspace_id: str, timeout_seconds: int = 10):
        """
        Initializes an isolated environment for a specific agent task.
        """
        self.client = docker.from_env()   # Handshake. Scans your system environment variables to look for Docker Desktop running on your PC
        self.workspace_id = workspace_id # A unique string given to each agent session so code files don't mix up or overwrite each other
        self.timeout = timeout_seconds
        
        # Define a secure, isolated directory on your host machine for this runtime
        # Using a relative path inside your project directory keeps things clean
        self.host_workspace = Path(os.getcwd()) / "sandboxes" / workspace_id
        self.host_workspace.mkdir(parents=True, exist_ok=True)
        
    def write_file(self, filename: str, content: str):
        """
        Safely writes code generated by the LLM into the sandbox workspace.
        """
        file_path = self.host_workspace / filename
        file_path.write_text(content, encoding="utf-8")
        print(file_path)

    def execute_command(self, command: str) -> dict:
        """
        Runs a shell command inside the container and traps the exit code and logs.
        """
        container = None
        try:
            # Spin up a heavily restricted python-slim container
            container = self.client.containers.run(
                image="python:3.11-slim",
                command=f"sh -c '{command}'",
                volumes={                                  # This is the magic bridge configuration. It takes your folder path from your laptop (str(self.host_workspace)) and glues it directly to a folder called /workspace inside the Linux container.
                    str(self.host_workspace): {
                        'bind': '/workspace',
                        'mode': 'rw' # Read-write access inside the container
                    }
                },
                working_dir='/workspace',
                detach=True, # Run the container in the background asynchronously so it doesn’t lock up your main Python backend script while waiting
                mem_limit="256m",     # Limits RAM to prevent memory leak crashes
                nano_cpus=1000000000, # Max 1 CPU core to prevent CPU exhaustion
                network_disabled=False, 
                user="1000:1000"      # Run as standard user, not root (admin)
            )

            # Wait for the container to finish executing or hit the timeout limit
            result = container.wait(timeout=self.timeout)
            logs = container.logs(stdout=True, stderr=True).decode("utf-8")
            
            return {
                "exit_code": result.get("StatusCode", -1),
                "output": logs
            }

        except docker.errors.ContainerError as e:
            return {"exit_code": -1, "output": str(e)}
        except Exception as e:
            # Handle timeout exceptions gracefully if code gets stuck in an infinite loop
            return {
                "exit_code": 124, 
                "output": f"Timeout Error: Execution exceeded {self.timeout} seconds.\nDetails: {str(e)}"
            }
        finally:
            # CRITICAL: Always clean up and remove the container to avoid cluttering your system
            if container:
                try:
                    container.remove(force=True)
                except:
                    pass

    def cleanup(self):
        """
        Purges the workspace files from your physical hard drive when the task completes.
        """
        if self.host_workspace.exists():
            shutil.rmtree(self.host_workspace)